var workouts = [{
    name:"Workout 1", instructions:[
        {todo:"Warm up walk", time:300},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
    ]},{
    name:"Workout 2", instructions:[
        {todo:"Warm up walk", time:300},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
    ]},{
    name:"Workout 3", instructions:[
        {todo:"Warm up walk", time:300},
        {todo:"Jog", time:90},
        {todo:"Walk", time:90},
        {todo:"Jog", time:180},
        {todo:"Walk", time:180},
        {todo:"Jog", time:90},
        {todo:"Walk", time:90},
        {todo:"Jog", time:180},
        {todo:"Walk", time:180},
    ]},{
    name:"The Scientific 7-Minute Workout", instructions:[
        {todo:"Jumping Jacks", time:30},
        {todo:"Rest", time:10},
        {todo:"Wall Sit", time:30},
        {todo:"Rest", time:10},
        {todo:"Push Ups", time:30},
        {todo:"Rest", time:10},
        {todo:"Abdominal Crunchs", time:30},
        {todo:"Rest", time:10},
        {todo:"Step on to chair", time:30},
        {todo:"Plank", time:30},
        {todo:"Rest", time:10},
        {todo:"High knees running in place", time:30},
        {todo:"Rest", time:10},
        {todo:"Lunge", time:30},
        {todo:"Rest", time:10},
        {todo:"Push up Roatation", time:30},
        {todo:"Rest", time:10},
        {todo:"Sideways Plank", time:30},
    ]}
];
