var workouts = [{
    name:"Workout 1", instructions:[
        {todo:"Warm up walk", time:300},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
    ]},{
    name:"Workout 2", instructions:[
        {todo:"Warm up walk", time:300},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
    ]}
];