var workouts = [{
    name:"Workout 1", instructions:[
        {todo:"Warm up walk", time:300},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90},
        {todo:"Jog", time:60},
        {todo:"Walk", time:90}
    ]},{
    name:"Workout 2", instructions:[
        {todo:"Warm up walk", time:300},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120},
        {todo:"Jog", time:90},
        {todo:"Walk", time:120}
    ]},{
    name:"Workout 3", instructions:[
        {todo:"Warm up walk", time:300},
        {todo:"Jog", time:90},
        {todo:"Walk", time:90},
        {todo:"Jog", time:180},
        {todo:"Walk", time:180},
        {todo:"Jog", time:90},
        {todo:"Walk", time:90},
        {todo:"Jog", time:180},
        {todo:"Walk", time:180}
    ]},{
        name:"Workout 4", instructions:[
        {todo:"Warm up walk", time:300},
        {todo:"Jog", time:180},
        {todo:"Walk", time:90},
        {todo:"Jog", time:300},
        {todo:"Walk", time:150},
        {todo:"Jog", time:180},
        {todo:"Walk", time:90},
        {todo:"Jog", time:300}
    ]},{
    name:"The Scientific Workout", instructions:[
        {todo:"Jumping Jacks", time:30},
        {todo:"Rest", time:10},
        {todo:"Wall Sit", time:30},
        {todo:"Rest", time:10},
        {todo:"Push Ups", time:30},
        {todo:"Rest", time:10},
        {todo:"Abdominal Crunchs", time:30},
        {todo:"Rest", time:10},
        {todo:"Step on to chair", time:30},
        {todo:"Rest", time:10},
        {todo:"Plank", time:30},
        {todo:"Rest", time:10},
        {todo:"High knees running in place", time:30},
        {todo:"Rest", time:10},
        {todo:"Lunge", time:30},
        {todo:"Rest", time:10},
        {todo:"Push up Roatation", time:30},
        {todo:"Rest", time:10},
        {todo:"Sideways Plank", time:30}
    ]},{
    name:"The WFH Workout", instructions:[
        {todo:"Jumping Jacks", time:30},
        {todo:"Rest", time:10},
        {todo:"Wall Sit", time:30},
        {todo:"Rest", time:10},
        {todo:"Push Ups", time:30},
        {todo:"Rest", time:10},
        {todo:"Abdominal Crunchs", time:30},
        {todo:"Rest", time:10},
        {todo:"Heel flicks", time:30},
        {todo:"Rest", time:10},
        {todo:"Plank", time:30},
        {todo:"Rest", time:10},
        {todo:"High knees running in place", time:30},
        {todo:"Rest", time:10},
        {todo:"Lunge", time:30},
        {todo:"Rest", time:10},
        {todo:"Mountain Climbers", time:30},
        {todo:"Rest", time:10},
        {todo:"Squats", time:30},
        {todo:"Rest", time:90},
        {todo:"Jog", time:300},
        {todo:"Rest", time:90},
        {todo:"Jumping Jacks", time:30},
        {todo:"Rest", time:10},
        {todo:"Wall Sit", time:30},
        {todo:"Rest", time:10},
        {todo:"Push Ups", time:30},
        {todo:"Rest", time:10},
        {todo:"Abdominal Crunchs", time:30},
        {todo:"Rest", time:10},
        {todo:"Heel flicks", time:30},
        {todo:"Rest", time:10},
        {todo:"Plank", time:30},
        {todo:"Rest", time:10},
        {todo:"High knees running in place", time:30},
        {todo:"Rest", time:10},
        {todo:"Lunge", time:30},
        {todo:"Rest", time:10},
        {todo:"Mountain Climbers", time:30},
        {todo:"Rest", time:10},
        {todo:"Squats", time:30}
    ]},{
    name:"Rugbybricks Passing Drill", instructions:[
        {todo:"Pitta Patter", time:50},
        {todo:"Rest", time:10},
        {todo:"Round the back right", time:50},
        {todo:"Rest", time:10},
        {todo:"Round the back left", time:50},
        {todo:"Rest", time:10},
        {todo:"Figure 8 between legs", time:50},
        {todo:"Rest", time:10},
        {todo:"Round the legs step back right", time:50},
        {todo:"Rest", time:10},
        {todo:"Round the legs step back left", time:50},
        {todo:"Rest", time:10},
        {todo:"Pass between the legs", time:50},
        {todo:"Rest", time:10},
        {todo:"Pistol Up right hand", time:50},
        {todo:"Rest", time:10},
        {todo:"Pistol Up left hand", time:50},
        {todo:"Rest", time:10},
        {todo:"Both hands straight up right hand", time:50},
        {todo:"Rest", time:10},
        {todo:"Both hands straight up left hand", time:50}
    ]}
];
